### ISSUE TITLE
hotstrings

### ISSUE THREAD

**Issue by knobhead** [cryzed/bin#3]
@cryzed You, Sir, are my personal hero. Thanks for hotstrings. 😍

**Comment by cryzed** [comment]
I'm always happy to hear when someone enjoys one of my projects; I'm glad you are finding it useful, thank you for your feedback -- it is greatly appreciated.

Could you maybe tell me how you found this repository, or hotstrings specifically? I'm a bit curious.

**Comment by knobhead** [comment]
was googling for AHK alternatives for linux and stumpled upon your [reddit](https://www.reddit.com/r/archlinux/comments/4xazrx/hotstrings_a_small_utility_to_automatically/) advert. :-)
