### ISSUE TITLE
hotstring to reload either hotstrings.py or hotstrings.json?

### ISSUE THREAD

**Issue by knobhead** [cryzed/bin#4]
Since especially in the beginning I had to do some tweaking to the `hotstrings.json`, I was looking for a way to reload either just the `hotstrings.json` or the whole python script. I was fiddling around a bit but didn't succeed.

My **first approach** was to add a hotstring that would launch a new instance of the python script and kill the old instance:

```json
{
  "!reload!":  ["run", "sh", "-c", "export pidold=$(pgrep -f ^python.*hotstrings$); setsid /my/path/to/hotstrings; kill -s 9 $pidold"],
  "/* here go my other hotstrings */"
}
```

My **second approach** was to add a new 'action' to `hotstrings.py` around line 207-ish:

```python
            ...
            elif action == 'reload':
                # make some python self-spawning magic happen here
                continue
            ...
```

But I was too tired and too new to python to think that through.

I'm sure you have a simple solution to that :-)

**Comment by cryzed** [comment]
Sorry for the (very) late answer -- this would be a neat feature, yes but I don't think it's _really_ needed for now. I mean how often do you change the hotstrings configuration after the initial setup? It would be too much added complexity for a very seldomly used feature. If more people at some point request this feature I'll consider adding it, promise.

Again sorry for the late reply.
